// @ts-nocheck
// AUTO-GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listDevices() : Promise<Result<DeviceMetadataDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDeviceHistory() : Promise<Result<DeviceHistoryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_device_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<SettingsDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestReset(mac: [number, number, number, number, number, number], kind: ResetKindDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_reset", { mac, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceRotationOffset(mac: [number, number, number, number, number, number], deg: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_device_rotation_offset", { mac, deg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogBuffer() : Promise<Result<LogEntryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_buffer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartSynthetic(count: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_synthetic", { count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
deviceDiscovered: DeviceDiscovered,
deviceHistoryUpdated: DeviceHistoryUpdated,
deviceStateChanged: DeviceStateChanged,
logEntry: LogEntry,
trackerUpdate: TrackerUpdate
}>({
deviceDiscovered: "device-discovered",
deviceHistoryUpdated: "device-history-updated",
deviceStateChanged: "device-state-changed",
logEntry: "log-entry",
trackerUpdate: "tracker-update"
})

/** user-defined constants **/



/** user-defined types **/

export type DeviceConnState = "connected" | "disconnected"
export type DeviceDiscovered = { metadata: DeviceMetadataDto }
export type DeviceHistoryDto = { mac: [number, number, number, number, number, number]; serial: string; kind: string; last_seen: number; rotation_deg: number }
export type DeviceHistoryUpdated = { rows: DeviceHistoryDto[] }
export type DeviceMetadataDto = { mac: [number, number, number, number, number, number]; serial: string; kind: string; firmware: string | null; has_magnetometer: boolean; has_battery: boolean; has_rumble: boolean; native_imu_rate_hz: number }
export type DeviceStateChanged = { mac: [number, number, number, number, number, number]; state: DeviceConnState }
export type IpcError = { type: "NotFound" } | { type: "Invalid"; message: string } | { type: "Internal"; message: string }
export type LogEntry = { ts_ms: number; level: string; target: string; message: string }
export type LogEntryDto = { ts_ms: number; level: string; target: string; message: string }
export type ResetKindDto = "yaw" | "full" | "mounting"
export type SettingsDto = { slime_server_addr: string; log_filter: string; theme: string; auto_start_synthetic: boolean }
export type TrackerSnapshot = { mac: [number, number, number, number, number, number]; serial: string; quat_xyzw: [number, number, number, number]; battery_fraction: number; rate_hz: number }
export type TrackerUpdate = { trackers: TrackerSnapshot[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
