// @ts-nocheck
// AUTO-GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listDevices() : Promise<Result<DeviceMetadataDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDeviceHistory() : Promise<Result<DeviceHistoryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_device_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<SettingsDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestReset(mac: [number, number, number, number, number, number], kind: ResetKindDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_reset", { mac, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDeviceRotationOffset(mac: [number, number, number, number, number, number], deg: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_device_rotation_offset", { mac, deg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogBuffer() : Promise<Result<LogEntryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_buffer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartSynthetic(count: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_synthetic", { count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Synchronous read of the current connection status. Tauri also emits
 * the same payload as `connection-status-update` ~1 Hz; this command is
 * useful for first paint when the UI mounts.
 */
async getConnectionStatus() : Promise<Result<ConnectionStatusUpdate, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPerDeviceSettings(mac: [number, number, number, number, number, number]) : Promise<Result<PerDeviceSettingsDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_per_device_settings", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFusionAlgo(mac: [number, number, number, number, number, number], algo: FusionAlgoDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_fusion_algo", { mac, algo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMountingOrientation(mac: [number, number, number, number, number, number], orientation: MountingOrientationDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mounting_orientation", { mac, orientation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMagnetometerEnabled(mac: [number, number, number, number, number, number], enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_magnetometer_enabled", { mac, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the OS file manager at the rolling-log directory. Used by the
 * "Diagnostics → Open logs folder" button so the tester can attach the
 * log file when reporting an issue.
 */
async openLogsDir() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the OS file manager at the persistence-DB directory (where
 * `state.db` lives). Useful for backing up settings or sharing state
 * dumps for support.
 */
async openDataDir() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a user-provided label for a tracker. Pure metadata — never
 * forwarded to SlimeVR-Server (body assignment lives there).
 */
async setTrackerLabel(mac: [number, number, number, number, number, number], label: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tracker_label", { mac, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackerHidden(mac: [number, number, number, number, number, number], hidden: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tracker_hidden", { mac, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackerOrder(mac: [number, number, number, number, number, number], order: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tracker_order", { mac, order }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackerGroup(mac: [number, number, number, number, number, number], group: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tracker_group", { mac, group }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the global UDP-emission gate. While paused the pipeline keeps
 * reading IMU samples and updating fusion state, but no rotation /
 * accel / battery packets leave for SlimeVR-Server. Reset / handshake
 * commands are unaffected.
 */
async setEmissionPaused(paused: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_emission_paused", { paused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEmissionPaused() : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_emission_paused") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOutputProfile(mac: [number, number, number, number, number, number]) : Promise<Result<OutputProfileDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_output_profile", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOutputProfile(mac: [number, number, number, number, number, number], profile: OutputProfileDto, applyNow: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_output_profile", { mac, profile, applyNow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pulse a controller's rumble motor briefly so a tester can confirm the
 * device receives commands. Clamped to 1500 ms server-side to avoid
 * runaway motors if the frontend forgets to send the stop. No-op if the
 * device is gone or has no rumble.
 */
async testRumble(mac: [number, number, number, number, number, number], durationMs: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_rumble", { mac, durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCalibrationWizardStatus(mac: [number, number, number, number, number, number]) : Promise<Result<CalibrationWizardStatusDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_calibration_wizard_status", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyCalibrationWizard(mac: [number, number, number, number, number, number], mounting: MountingOrientationDto, rotationOffsetDeg: number, magnetometerEnabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_calibration_wizard", { mac, mounting, rotationOffsetDeg, magnetometerEnabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAdvancedTelemetry() : Promise<Result<AdvancedTelemetryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_advanced_telemetry") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Begin a magnetometer calibration session for one device. The user then
 * rotates the device through all orientations while the pipeline collects
 * samples; the UI polls [`get_mag_cal_progress`].
 */
async startMagCalibration(mac: [number, number, number, number, number, number]) : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_mag_calibration", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abort an in-progress calibration session, discarding collected samples.
 */
async cancelMagCalibration(mac: [number, number, number, number, number, number]) : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_mag_calibration", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Finish a calibration session: fit the sphere, persist the result, enable
 * the magnetometer, and apply it to the running pipeline. Errors if the fit
 * failed (too few or poorly-spread samples — rotate more and retry).
 */
async finishMagCalibration(mac: [number, number, number, number, number, number]) : Promise<Result<MagCalibrationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finish_mag_calibration", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Latest progress of an in-flight calibration session, or an inactive
 * snapshot if none is running.
 */
async getMagCalProgress(mac: [number, number, number, number, number, number]) : Promise<Result<MagCalProgressDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mag_cal_progress", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The persisted hard-iron calibration for a device, or `None` if uncalibrated.
 */
async getMagCalibration(mac: [number, number, number, number, number, number]) : Promise<Result<MagCalibrationDto | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mag_calibration", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Discard a device's persisted calibration. The magnetometer stops feeding
 * fusion until the device is recalibrated.
 */
async clearMagCalibration(mac: [number, number, number, number, number, number]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_mag_calibration", { mac }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHapticConfig() : Promise<Result<HapticConfigDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_haptic_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHapticConfig(config: HapticConfigDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_haptic_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
biasUpdate: BiasUpdate,
connectionStatusUpdate: ConnectionStatusUpdate,
deviceDiscovered: DeviceDiscovered,
deviceHistoryUpdated: DeviceHistoryUpdated,
deviceStateChanged: DeviceStateChanged,
hapticAddressDiscovered: HapticAddressDiscovered,
imuSampleUpdate: ImuSampleUpdate,
latencyUpdate: LatencyUpdate,
logEntry: LogEntry,
trackerUpdate: TrackerUpdate
}>({
biasUpdate: "bias-update",
connectionStatusUpdate: "connection-status-update",
deviceDiscovered: "device-discovered",
deviceHistoryUpdated: "device-history-updated",
deviceStateChanged: "device-state-changed",
hapticAddressDiscovered: "haptic-address-discovered",
imuSampleUpdate: "imu-sample-update",
latencyUpdate: "latency-update",
logEntry: "log-entry",
trackerUpdate: "tracker-update"
})

/** user-defined constants **/



/** user-defined types **/

export type AdvancedTelemetryDto = { mac: [number, number, number, number, number, number]; serial: string; sample_rate_hz: number; battery_fraction: number; gyro_norm_rads: number; accel_norm_mps2: number; mag_norm_u_t: number | null; gyro_bias_rads: [number, number, number]; orientation_xyzw: [number, number, number, number]; sample_age_ms: number }
export type BiasEntry = { mac: [number, number, number, number, number, number]; gyr_bias: [number, number, number] }
export type BiasUpdate = { entries: BiasEntry[] }
export type CalibrationWizardStatusDto = { suggested_mounting: MountingOrientationDto; suggested_rotation_offset_deg: number; accel_norm_mps2: number; gyro_norm_rads: number; sample_age_ms: number }
export type ConnectionStatusUpdate = { server_addr: string; server_supports_bundle: boolean; packets_sent: number; last_send_ms_ago: number | null; last_handshake_ms_ago: number | null }
export type DeviceConnState = "connected" | "disconnected"
export type DeviceDiscovered = { metadata: DeviceMetadataDto }
export type DeviceHistoryDto = { mac: [number, number, number, number, number, number]; serial: string; kind: string; last_seen: number; rotation_deg: number }
export type DeviceHistoryUpdated = { rows: DeviceHistoryDto[] }
export type DeviceMetadataDto = { mac: [number, number, number, number, number, number]; serial: string; kind: string; firmware: string | null; has_magnetometer: boolean; has_battery: boolean; has_rumble: boolean; native_imu_rate_hz: number }
export type DeviceStateChanged = { mac: [number, number, number, number, number, number]; state: DeviceConnState }
export type FusionAlgoDto = "vqf" | "madgwick" | "basic_vqf"
/**
 * Snapshot of the SlimeClient runtime state for the Connection panel.
 * Emitted ~1 Hz and also returned synchronously by the
 * `get_connection_status` command for first paint.
 * A distinct OSC address the haptic bridge has observed from VRChat.
 * The haptics config UI listens for these so the user can tap an avatar
 * contact in-game and bind the address that lights up.
 */
export type HapticAddressDiscovered = { address: string }
export type HapticConfigDto = { enabled: boolean; listen_port: number; rules: HapticRuleDto[] }
export type HapticModeDto = { kind: "proximity"; gain: number; min_threshold: number } | { kind: "pulse"; pulse_ms: number }
export type HapticRuleDto = { osc_address: string; 
/**
 * Target device MAC as 12 lowercase hex chars (no separators).
 */
device_mac: string; mode: HapticModeDto }
/**
 * One raw IMU sample per known device at the emitter cadence (~30 Hz).
 * Frame is the device-native body frame.
 */
export type ImuSampleEntry = { mac: [number, number, number, number, number, number]; gyr_xyz: [number, number, number]; acc_xyz: [number, number, number]; mag_xyz: [number, number, number] | null; elapsed_ms: number }
export type ImuSampleUpdate = { samples: ImuSampleEntry[] }
export type IpcError = { type: "NotFound" } | { type: "Invalid"; message: string } | { type: "Internal"; message: string }
/**
 * Per-tracker latency / jitter snapshot for the diagnostics panel.
 * Pure bridge telemetry — no fusion or motion data, just how the bridge
 * itself is performing (inter-batch interval, UDP send call duration,
 * rough drop estimate from interval gaps).
 */
export type LatencyEntry = { mac: [number, number, number, number, number, number]; interval_us_p50: number; interval_us_p95: number; interval_us_p99: number; jitter_us: number; send_us_p50: number; send_us_p95: number; dropped_estimate: number; samples_window: number }
export type LatencyUpdate = { entries: LatencyEntry[] }
export type LogEntry = { ts_ms: number; level: string; target: string; message: string }
export type LogEntryDto = { ts_ms: number; level: string; target: string; message: string }
/**
 * Live progress of an in-flight calibration session.
 */
export type MagCalProgressDto = { active: boolean; n_samples: number; 
/**
 * Coverage 0.0..=1.0 — drives the "rotate the device" progress ring.
 */
coverage: number; field_strength_ut: number }
/**
 * Persisted hard-iron calibration, frontend-facing.
 */
export type MagCalibrationDto = { 
/**
 * Hard-iron offset (µT) subtracted from raw magnetometer samples.
 */
offset: [number, number, number]; 
/**
 * Fitted field magnitude (µT). Earth's field is ~25-65 µT.
 */
field_strength_ut: number; 
/**
 * Sphere-fit RMS residual (µT) — lower is a tighter fit.
 */
residual: number; 
/**
 * Direction-bin coverage 0.0..=1.0 of the calibration sample set.
 */
coverage: number }
export type MountingOrientationDto = "identity" | "left_side" | "right_side" | "upside_down" | "facing_forward" | "facing_back"
export type OutputProfileDto = { led_mask: number; rumble_enabled: boolean }
export type PerDeviceSettingsDto = { fusion: FusionAlgoDto; mounting: MountingOrientationDto; magnetometer_enabled: boolean; rotation_offset_deg: number; 
/**
 * Optional user-provided label ("right shin", "head") — purely
 * informational on the bridge side; SlimeVR-Server owns body
 * assignment and would override anything we put in tracker_position.
 */
label: string; 
/**
 * When true, this tracker is hidden from the Dashboard list
 * (Devices page still shows it with an unhide affordance). UI-only;
 * pipeline keeps emitting to SlimeVR-Server.
 */
hidden: boolean; 
/**
 * Display order on the Dashboard / Devices pages. Lower sorts
 * first; ties broken by insertion order. Set by drag-reorder UX.
 */
display_order: number; 
/**
 * Free-form group label ("L-leg", "R-arm") for visual grouping +
 * broadcast-to-group resets. UI-only; SlimeVR-Server never sees it.
 */
group: string }
export type ResetKindDto = "yaw" | "full" | "mounting"
export type SettingsDto = { slime_server_addr: string; log_filter: string; theme: string; auto_start_synthetic: boolean; 
/**
 * When true, clicking the window close button hides the window to
 * the tray instead of exiting. Quit is still reachable via the
 * tray menu's Quit entry. Default false to match pre-tray behavior.
 */
close_to_tray: boolean }
export type TrackerSnapshot = { mac: [number, number, number, number, number, number]; serial: string; quat_xyzw: [number, number, number, number]; battery_fraction: number; rate_hz: number }
export type TrackerUpdate = { trackers: TrackerSnapshot[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
