//! everything-imu Tauri 2 binary entrypoint.

pub mod commands;
pub mod crash_report;
pub mod dto;
pub mod error;
pub mod events;
pub mod haptics;
pub mod logging;
pub mod state;
pub mod steam_blacklist;
pub mod supervisor_boot;
pub mod tracker_emitter;
pub mod tray;
pub mod udev_install;
pub mod udp_haptic;
pub mod update_boot;
pub mod updater;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Workaround for Linux NVIDIA + WebKitGTK bug causing blank/crashing windows.
    // Disabling DMA-BUF forces fallback rendering, fixing the issue transparently for users.
    #[cfg(target_os = "linux")]
    std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");

    let specta_builder = build_specta();

    #[cfg(debug_assertions)]
    {
        let bindings_path = "../../apps/ui/src/api/bindings.ts";
        specta_builder
            .export(
                specta_typescript::Typescript::default()
                    .bigint(specta_typescript::BigIntExportBehavior::Number)
                    .header("// AUTO-GENERATED by tauri-specta. Do not edit.\n"),
                bindings_path,
            )
            .expect("specta export");
        prepend_ts_nocheck(bindings_path);
    }

    tauri::Builder::default()
        // Single-instance MUST be registered first per the plugin's docs —
        // it short-circuits subsequent launches before any other plugin
        // initialization runs. The callback brings the existing window
        // forward instead of spawning a second tray / window / pipeline.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            tracing::info!("second-launch attempt intercepted; focusing existing window");
            tray::focus_main(app);
        }))
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .on_window_event(|window, event| {
            use tauri::Manager;
            // Only the main window participates in close-to-tray; other
            // windows (future mini-mode etc.) close normally.
            if window.label() != "main" {
                return;
            }
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let app = window.app_handle();
                let close_to_tray = app
                    .try_state::<state::AppHandle>()
                    .and_then(|h| h.db.get_setting("close_to_tray").ok().flatten())
                    .map(|v| v == "1")
                    .unwrap_or(false);
                if close_to_tray {
                    api.prevent_close();
                    let _ = window.hide();
                }
                // else: let the default close proceed. Tauri tears the
                // window down and the process exits once no windows remain.
            }
        })
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);

            let db_path = {
                let dir = tauri::Manager::path(app)
                    .app_data_dir()
                    .expect("app_data_dir");
                std::fs::create_dir_all(&dir).ok();
                dir.join("state.db")
            };
            let db = std::sync::Arc::new(persistence::PersistenceDb::open(&db_path)?);

            let settings: std::sync::Arc<dyn device_traits::SettingsStore> =
                std::sync::Arc::new(persistence::SqliteSettingsStore::new(db.clone()));
            let bias: std::sync::Arc<dyn device_traits::BiasStore> =
                std::sync::Arc::new(persistence::SqliteBiasStore::new(db.clone()));

            let server_addr: std::net::SocketAddr = db
                .get_setting("slime_server_addr")
                .ok()
                .flatten()
                .and_then(|v| v.parse().ok())
                .unwrap_or_else(|| "127.0.0.1:6969".parse().unwrap());
            let auto_start_synthetic = db
                .get_setting("auto_start_synthetic")
                .ok()
                .flatten()
                .map(|v| v == "1")
                .unwrap_or(false);
            let crash_report_enabled = db
                .get_setting("crash_report_enabled")
                .ok()
                .flatten()
                .map(|v| v == "1")
                .unwrap_or(false);
            crash_report::init_if_opted_in(crash_report_enabled);

            let state = tauri::async_runtime::block_on(async {
                std::sync::Arc::new(
                    everything_imu_core::AppState::new(server_addr, settings, bias)
                        .await
                        .expect("AppState::new"),
                )
            });

            let log_buffer: std::sync::Arc<
                parking_lot::Mutex<std::collections::VecDeque<dto::LogEntryDto>>,
            > = std::sync::Arc::new(parking_lot::Mutex::new(std::collections::VecDeque::new()));
            let log_layer = logging::UiLayer {
                buffer: log_buffer.clone(),
                app: app.handle().clone(),
            };

            // Rolling file appender at <app_data_dir>/logs/everything-imu.log
            // (daily rotation, retains the last 7 files). The non-blocking
            // worker guard must outlive the subscriber, so we leak it once at
            // startup — this is a one-time deliberate leak; the OS reclaims
            // the descriptors on exit. See tracing-appender's docs.
            let log_dir = {
                let dir = tauri::Manager::path(app)
                    .app_data_dir()
                    .expect("app_data_dir")
                    .join("logs");
                std::fs::create_dir_all(&dir).ok();
                dir
            };
            let file_appender = tracing_appender::rolling::Builder::new()
                .rotation(tracing_appender::rolling::Rotation::DAILY)
                .filename_prefix("everything-imu")
                .filename_suffix("log")
                .max_log_files(7)
                .build(&log_dir)
                .expect("rolling file appender");
            let (file_writer, file_guard) = tracing_appender::non_blocking(file_appender);
            Box::leak(Box::new(file_guard));

            use tracing_subscriber::prelude::*;
            let _ = tracing_subscriber::registry()
                .with(tracing_subscriber::fmt::layer())
                .with(
                    tracing_subscriber::fmt::layer()
                        .with_ansi(false)
                        .with_writer(file_writer),
                )
                .with(log_layer)
                .try_init();
            tracing::info!(?log_dir, "log file rolling daily, retain 7 days");

            // Start the OSC haptic bridge before managing AppHandle so its
            // live-config sender can be stored for the haptics commands.
            let haptic_config = haptics::load_config(&db);
            let haptic_config_tx =
                haptics::spawn(app.handle(), state.clone(), haptic_config);

            tauri::Manager::manage(
                app,
                state::AppHandle {
                    state: state.clone(),
                    db: db.clone(),
                    log_buffer,
                    haptic_config_tx,
                },
            );

            tray::init_tray_or_warn(app.handle());
            tracker_emitter::spawn(app.handle());
            supervisor_boot::spawn(app.handle(), auto_start_synthetic);
            update_boot::spawn(app.handle());

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("tauri run");
}

/// Prepend `// @ts-nocheck` to a generated bindings file. Needed because
/// tauri-specta always emits an unused `Channel as TAURI_CHANNEL` import,
/// which the strict project tsconfig (noUnusedLocals) rejects. specta's
/// `.header()` only honors the first line, so post-processing is the
/// least invasive fix until tauri-specta gains a pragma option.
pub fn prepend_ts_nocheck(path: &str) {
    let body = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(_) => return,
    };
    if body.contains("// @ts-nocheck") {
        return;
    }
    let _ = std::fs::write(path, format!("// @ts-nocheck\n{body}"));
}

/// Builder factory for both runtime export (in `run()`) and the
/// `examples/gen_bindings.rs` standalone binary used by CI to validate
/// idempotency without launching the Tauri webview.
pub fn build_specta() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::list_devices,
            commands::list_device_history,
            commands::get_settings,
            commands::set_setting,
            commands::request_reset,
            commands::set_device_rotation_offset,
            commands::set_gyro_scale,
            commands::get_log_buffer,
            commands::restart_synthetic,
            commands::get_connection_status,
            commands::get_per_device_settings,
            commands::set_fusion_algo,
            commands::set_mounting_orientation,
            commands::set_magnetometer_enabled,
            commands::open_logs_dir,
            commands::open_data_dir,
            commands::set_tracker_label,
            commands::set_tracker_hidden,
            commands::set_tracker_order,
            commands::set_tracker_group,
            commands::set_emission_paused,
            commands::get_emission_paused,
            commands::get_output_profile,
            commands::set_output_profile,
            commands::test_rumble,
            commands::test_rumble_at,
            commands::get_haptic_calibration,
            commands::set_haptic_calibration,
            commands::get_calibration_wizard_status,
            commands::apply_calibration_wizard,
            commands::get_advanced_telemetry,
            commands::start_mag_calibration,
            commands::cancel_mag_calibration,
            commands::finish_mag_calibration,
            commands::get_mag_cal_progress,
            commands::get_mag_calibration,
            commands::clear_mag_calibration,
            haptics::get_haptic_config,
            haptics::set_haptic_config,
            commands::steam_blacklist_check,
            commands::steam_blacklist_apply_fix,
            commands::check_for_update,
            commands::apply_update,
            commands::install_udev_rules,
            commands::udp_haptic_list,
            commands::udp_haptic_upsert,
            commands::udp_haptic_remove,
            commands::udp_haptic_test,
        ])
        .events(tauri_specta::collect_events![
            events::TrackerUpdate,
            events::DeviceDiscovered,
            events::DeviceStateChanged,
            events::LogEntry,
            events::DeviceHistoryUpdated,
            events::ImuSampleUpdate,
            events::BiasUpdate,
            events::LatencyUpdate,
            events::ConnectionStatusUpdate,
            events::HapticAddressDiscovered,
            events::UpdateStatus,
        ])
}
